<?php
$data = array (
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '中介贸易',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => '3',
    'level' => 0,
    'id' => '50',
    'name' => '中介贸易',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '屠宰',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '53',
    'name' => '屠宰',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '设备',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '54',
    'name' => '设备',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '幼崽',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '51',
    'name' => '幼崽',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '兽医',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '兽医',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '饲料',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '饲料',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '屠宰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '59',
    'name' => '屠宰',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '大牲畜',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '62',
    'name' => '大牲畜',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '药品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '56',
    'name' => '药品',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '大牲畜药',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '24',
    'name' => '大牲畜药',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '仔畜专用药',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '30',
    'name' => '仔畜专用药',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '呼吸道药',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '27',
    'name' => '呼吸道药',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '营养保健药',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '31',
    'name' => '营养保健药',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '肠炎驱虫药',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '肠炎驱虫药',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '消炎药',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '25',
    'name' => '消炎药',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '消毒剂',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '消毒剂',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '孕畜专用药',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '孕畜专用药',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '抗病毒药',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '26',
    'name' => '抗病毒药',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '脱霉剂',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '33',
    'name' => '脱霉剂',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '水产用药',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '水产用药',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '螃蟹药',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '46',
    'name' => '螃蟹药',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '水环境改善药',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '43',
    'name' => '水环境改善药',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '龟鳖药',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '47',
    'name' => '龟鳖药',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '鱼类药',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '44',
    'name' => '鱼类药',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '海产品药',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '48',
    'name' => '海产品药',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '虾类药',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '45',
    'name' => '虾类药',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '消毒药',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '42',
    'name' => '消毒药',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '渔药',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '49',
    'name' => '渔药',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '猪药',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => '猪药',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '营养保健药',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '21',
    'name' => '营养保健药',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '肠炎驱虫药',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '18',
    'name' => '肠炎驱虫药',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '消炎药',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '15',
    'name' => '消炎药',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '消毒剂',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '22',
    'name' => '消毒剂',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '母猪专用药',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '19',
    'name' => '母猪专用药',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '抗病毒药',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '16',
    'name' => '抗病毒药',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '脱霉剂',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '23',
    'name' => '脱霉剂',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '仔猪专用药',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '20',
    'name' => '仔猪专用药',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '呼吸道药',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '17',
    'name' => '呼吸道药',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '宠物用药',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '宠物用药',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '宠物清洁剂',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '40',
    'name' => '宠物清洁剂',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '肠炎驱虫药',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '37',
    'name' => '肠炎驱虫药',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '消炎药',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '消炎药',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '宠物食品',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '41',
    'name' => '宠物食品',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '孕畜专用药',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '38',
    'name' => '孕畜专用药',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '抗病毒药',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '35',
    'name' => '抗病毒药',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '营养保健药',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '39',
    'name' => '营养保健药',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '呼吸道药',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '36',
    'name' => '呼吸道药',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '禽药',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 1,
    'id' => '1',
    'name' => '禽药',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '蛋、种鸡专用药',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '14',
    'name' => '蛋、种鸡专用药',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '营养药',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '11',
    'name' => '营养药',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '呼吸道药',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '8',
    'name' => '呼吸道药',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '消毒剂',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '12',
    'name' => '消毒剂',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '肠炎球虫药',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '9',
    'name' => '肠炎球虫药',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '消炎药',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '6',
    'name' => '消炎药',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '腺胃炎药',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '3',
    'name' => '腺胃炎药',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '脱霉剂',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '13',
    'name' => '脱霉剂',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '保肝护肾药',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '10',
    'name' => '保肝护肾药',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '抗病毒药',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 2,
    'id' => '7',
    'name' => '抗病毒药',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '饲料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '57',
    'name' => '饲料',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '禽料',
    'measure_unit' => '',
    'parent_id' => '57',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '禽料',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '幼崽',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '58',
    'name' => '幼崽',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '禽雏',
    'measure_unit' => '',
    'parent_id' => '58',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '61',
    'name' => '禽雏',
  ),
);
?>