<?php
$data = array (
  'shop_name' => '云博畜牧商城',
  'shop_title' => '云博畜牧商城',
  'shop_desc' => '云博畜牧商城',
  'shop_keywords' => '云博畜牧商城',
  'shop_country' => '1',
  'shop_province' => '2',
  'shop_city' => '',
  'shop_address' => '',
  'qq' => '',
  'ww' => '',
  'skype' => '',
  'ym' => '',
  'msn' => '',
  'service_email' => '',
  'service_phone' => '',
  'shop_closed' => '0',
  'close_comment' => '',
  'shop_logo' => '',
  'licensed' => '1',
  'user_notice' => '每年38亿吨畜禽废弃物只利用六成 专家解读三方面原因
<div class="rich_media_content " id="js_content">
                    

                    

                    
                    
                    <p></p><p><span style="font-size: 14px;">我国每年生产1.5亿多吨肉蛋奶，与此同时，每年也产生38亿吨畜禽废弃物。这使得农业超过工业成为我国最大的面源污染产业，也给周边环境和居民生活带来不利的影响。今年中央一号文件再次明确提出，加强农业面源污染防治。</span></p><p><span style="font-size: 14px;">此前，全国畜牧总站站长、国家畜禽养殖废弃物资源化利用科技创新联盟理事长杨振海接受第一财经记者专访称，近些年，我国畜牧业持续稳定发展，综合生产能力显著增强，为保障城乡居民“菜篮子”产品有效供给、促进农牧民持续增收做出了重大贡献。</span></p><p><span style="font-size: 14px;">随着畜禽养殖总量不断扩大，也产生了大量的畜禽养殖废弃物。他认为，畜禽养殖废弃物可以通过综合利用的形式变废为宝，但是，总体来看，目前我国畜禽养殖废弃物综合利用比例还不高，有40%未有效处理和利用，造成资源的巨大浪费。</span></p><p><span style="font-size: 14px;">禽养殖废弃物利用的三个难题</span></p><p><span style="font-size: 14px;">针对农业面源污染的问题，2016年12月21日，习近平总书记在中央财经领导小组第十四次会议上提出，加快推进畜禽养殖废弃物处理和资源化，关系 6亿多农村居民生产生活环境，关系农村能源革命，关系能不能不断改善土壤地力、治理好农业面源污染，是一件利国利民利长远的大好事。</span></p><p><span style="font-size: 14px;">2017年6月，国务院办公厅下发《关于加快推进畜牧养殖废弃物资源化利用的意见》。这是我国畜牧业发展史上第一个专门针对畜禽养殖废弃物处理和利用出台的指导性文件。</span></p><p><span style="font-size: 14px;">农业部官方数据显示，目前，全国畜禽粪污年产生量约38亿吨，其中畜禽直接排泄的粪便约18亿吨，养殖过程产生的污水量约20亿吨。从不同畜种来看，生猪是大头，全国生猪粪污年产生量约18亿吨，占总量的47%；牛粪污年产生量约14亿吨，占总量的37%，其中奶牛4亿吨、肉牛10亿吨；家禽粪污年产生量约6亿吨，占总量的16%。</span></p><p><span style="font-size: 14px;">其实畜禽养殖废弃物的资源化利用空间很大。杨振海举例称，堆沤等方式制作的农家肥、工厂化生产的商品有机肥和沼气工程产生的沼肥（沼渣、沼液），通过就近就地肥料化利用，对于改良土壤、培肥地力、促进农作物增产增收有重要作用，也是促进种养结合，实现农业绿色可持续发展的根本手段。据测算，全国畜禽固体粪便全部利用，年可生产有机肥3.5亿吨。</span></p><p><span style="font-size: 14px;">此外，能源化也是畜禽养殖废弃物利用的一个重要方向。目前一般通过建设沼气工程，对粪便等废弃物进行厌氧发酵处理，生产沼气、生物天然气或发电上网。能源化利用进一步拓展了粪便的资源价值，实现了高值高效利用，为农村提供了清洁可再生能源，减少了二氧化碳温室气体排放，促进了节能减排。据测算，全国畜禽粪便理论沼气产生量超过1000亿立方米，可发电1600亿千瓦时，具有较大的市场开发潜力。</span></p><p><span style="font-size: 14px;">在推动畜禽养殖废弃物资源化利用的具体推进过程中，杨振海还提到了三个主要困难：一是畜禽养殖与农业种植主体分离，种养结合不紧密，畜禽粪便还田难；二是一些地方畜禽养殖规模超出土地、水资源等环境可承受范围，畜牧业区域布局不平衡，畜禽养殖总量与环境容量不匹配，特别是南方水网地区，这个问题相对比较突出；三是一些地区过于强调畜禽养殖造成的污染问题，对发展畜牧业积极性不高，大幅度调减畜禽养殖规模，影响了畜牧业稳定发展和保障畜产品市场有效供给。</span></p><p><img class="img_loading" data-ratio="0.75" data-src="https://mmbiz.qpic.cn/mmbiz_jpg/37JHFXHWTIkNT7KTA3pzar6O71NRV0xga9FjdvDoy3GVCCYP6GjjNaahMINL06eQOcrmwvMcZhQVtVpwaSGULA/640?wx_fmt=jpeg" data-type="jpeg" data-w="640" height="480" style="-webkit-tap-highlight-color: transparent; box-sizing: border-box; border-style: none; display: block; margin: 10px auto; color: rgb(34, 34, 34); width: 640px !important; height: 480px !important;" width="640" src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg=="></p><p><span style="font-size: 14px;">弃物综合利用成本高</span></p><p><span style="font-size: 14px;">之所以我国畜禽养殖废弃物综合利用比例还不高，杨振海称，主要有三个方面的原因。</span></p><p><span style="font-size: 14px;">一是当前农牧结合的激励机制还没有真正形成。以前的小农户养猪时期，种养一体，一头肥猪实际上是一个小化肥厂。现在社会化分工越来越细，更加专业化，规模化养殖和种植发展迅速，养猪的不一定种地，种地的不一定养猪，种养分离，阻断了种养循环的路径。受土地资源制约，部分畜禽规模养殖场没有足够的配套消纳用地，加之缺少支持有机肥生产使用的专项政策，有机肥使用积极性不高，导致种养循环通道尚未打通，粪便出路不畅。</span></p><p><span style="font-size: 14px;">二是废弃物综合处理利用技术模式相对比较滞后。我国幅员辽阔，各地区气候、资源等自然生态条件差异较大，畜禽养殖方式千差万别，必须因地制宜采取有效的废弃物处理利用技术。但是，畜禽养殖废弃物资源化利用的技术研发工作起步比较晚，经济、高效的废弃物处理模式还不多。而且，畜禽固体粪便相对好处理，养殖污水处理难、利用难问题比较突出。目前，最普遍使用的沼气发酵处理模式，在实际生产中还存在工艺不配套问题，而且这种方式沼渣、沼液产生量多，对贮存、输送等配套设施要求高，沼液不能得到有效应用，易造成二次污染。</span></p><p><span style="font-size: 14px;">三是成本较高，部分养殖企业难以承受。畜禽养殖企业经济实力相对不强，粪污处理设施投资大、运行成本高，养殖企业特别是中等规模养殖场经济上难以承担。如果养殖企业采取工业化处理方式，通过建设大型工程设施对畜禽养殖污水进行深度处理，虽然可以实现达标排放或清洁循环利用，但基本建设成本和运行成本较高。从调研的情况看，目前只有极少部分资金实力雄厚的企业采用这种处理方式，大部分企业很难承受。</span></p><p><span style="font-size: 14px;">具体来说，以生猪规模养殖场来举例，对于年出栏1万头的大型养猪企业，粪污处理利用等环保设施投入约占养殖企业基础设施总投资的30%-35%，平均每出栏一头生猪的环保成本为25-40元。其中，具体投入根据不同的技术模式有所差异。</span></p><p><span style="font-size: 14px;">比如，如果采取粪污“能源化+肥料化”利用的方式，粪污处理设施设备的投资需要400万元左右，它的优点是既可以利用养殖废弃物发酵处理生产可再生清洁能源，解决周围农户和养殖场的生活燃料和日常用能，又可以与种植业相结合，利用沼渣沼液替代化肥和灌溉用水，生产高品质的农产品，促进农民增收。但其需要养殖场周围有足够配套的土地，而且由于种植业的季节性较强，在非灌溉或施肥时期，还需要有足够的设施对沼渣沼液进行贮存。</span></p><p><span style="font-size: 14px;">再比如，如果采取达标排放技术，粪污处理设施设备的投资需要500万元左右，这种模式的优点是不需要很多配套土地，但是建设投资和运行费用都很高，且污水处理系统技术复杂，要求有专业人员进行运行维护。</span></p><p><span style="font-size: 14px;">不能照搬国外补贴标准</span></p><p><span style="font-size: 14px;">国外发达国家由于畜禽养殖废弃物资源化利用起步早，技术模式也比较成熟，加之政府扶持，他们在建设现代畜牧业的进程中，不断完善其养殖废弃物资源化利用技术。</span></p><p><span style="font-size: 14px;">杨振海举例称，美国自然资源广袤丰富，人少地多，号称“耕二余一”，土地休耕也很普遍。无论是种地还是养猪，都是由大农场、大企业经营的。他们的规模5000头以上的养殖场占60%，并且都有足够的土地消纳粪污。他们从畜牧业的源头饲料，到资源化利用，整个链条中进行技术支持，各州的支持力度不尽相同。</span></p><p><span style="font-size: 14px;">在欧盟，自然资源并不富裕，人口相对密集，家庭农牧场主要走可持续发展的路子。对于畜禽养殖废弃物资源化利用，主要是制定有关法规制度，实行沼气发电补贴，对合规生产进行补助。</span></p><p><span style="font-size: 14px;">杨振海提到，这些政策主要是基于生态环保的目标设置的，补贴的计算基础是以前的收入和采用农业环保措施所需的经费奖励，具有合理性和持续性。比如，意大利牧场在建设沼气工程之初，给予牧场工程投资30%的补贴，同时保证以每度电0.28欧元的价格连续收购15年。这个价格高于国家购电0.21欧元，高于居民用电0.05欧元，牧场正常运转每年卖电收入可观。对于遵守环保政策的牧场，按照每100升牛奶4欧元的标准给予生产补贴，生产1000万升牛奶的牧场，每年可获补助40万欧元。</span></p><p><span style="font-size: 14px;">对于中国来说，人多地少，人均耕地资源有限，但养殖规模巨大，而且养殖场户很多。杨振海认为，可以借鉴发达国家补贴理念，学习发达国家的技术模式，但不能照搬其补贴标准。应该根据国情和实际，走自己的道路，重点对畜牧大县和规模养殖场开展废弃物资源化利用进行支持。</span></p><p><span style="font-size: 14px;">目前，农业部已确定了畜牧大县586个。2017年，财政部、农业部启动实施畜禽粪污资源化利用试点，安排20个亿，支持51个畜牧大县整县开展畜禽粪污资源化利用，中央财政通过以奖代补方式，对畜牧大县市场主体建设畜禽粪污集中处理设施和规模养殖场实现全量化有效处理进行适当支持。</span></p><p><span style="font-size: 14px;">此外，中央财政补助资金重点用于规模养殖场改进养殖工艺和设备，建设畜禽粪污收集、贮存、处理设施和输送管网，建设畜禽粪污集中处理和资源化利用设施等。同时，正在建设畜禽粪污资源化利用直联直报系统，对规模养殖场进行摸底调查，并及时跟踪规模养殖场废弃物资源化利用进展情况，为项目实施提供数据支撑。</span></p><section class="" data-source="bj.96weixin.com" style="white-space: normal;line-height: 25.6px;"><section style="margin-top: 0.5em;margin-bottom: 0.5em;"></section></section><p><br></p>
                </div>',
  'shop_notice' => '环保风暴又来？环保部直指各地环境积弊 8省份一把手挂帅整改
<div class="rich_media_content " id="js_content">
                    

                    

                    
                    
                    <p><span style="font-size: 14px;"></span></p><p></p><p><span style="color: rgb(255, 41, 65);"><strong><span style="font-size: 14px;">当下</span></strong></span><span style="font-size: 14px;">，有一件极为重要的整改工作摆在全国8省份一把手的案头。因为这件事，8省份不仅要在30个工作日内组织编制整改方案上报，并且还要将重要情况及时报告党中央、国务院。</span></p><p><span style="font-size: 14px;">事情还要从去年说起。2017年8月7日至9月15日，8个中央环境保护督察组分别对吉林、浙江、山东、海南、四川、西藏、青海、新疆（含兵团）等8省份开展了环境保护督察。</span></p><p><span style="font-size: 14px;">后经党中央、国务院批准，从12月22日开始，各督察组陆续向相关省份反馈督察意见，并同步移交督察发现的生态环境损害责任追究问题案卷。</span></p><p class=""></p><p><span style="font-size: 14px;">在环保部办公厅发布的文件中，直言不讳、甚至措辞严厉地直指各地环境积弊，例如“部分地方党委政府对环境保护认识尚不到位，环保不作为、乱作为，不担当、不碰硬的情况仍然存在”等等，还涉及大气和水环境问题、城市环境基础设施建设严重缺失、沿海地区违法围海填海和违规养殖情况常见、自然保护区局部生态破坏等具体问题。</span></p><p><span style="font-size: 14px;">此后，分赴各地的中央环保督察组先后召开了有8省份一把手参加的反馈会，明确细致指出了各地存在的问题。而一把手们也及时表态，表示要尽快解决被督查出的问题，恢复良好的生态环境。</span></p><p><span style="font-size: 14px;">长安街知事注意到，在这8场会后，各地纷纷开始了一场由一把手亲自挂帅的“环境保卫战”。</span></p><p><span style="font-size: 14px;"></span></p><p style="text-align: center;"></p><p><span style="font-size: 14px;"></span><br></p><p><span style="font-size: 14px;">在山东，省委、省政府已经成立省委书记刘家义、省长龚正任双组长的省环境保护督察反馈意见整改工作领导小组，下设5个专项工作组，多次召开整改工作协调推进会议，并将于近日召开整改动员大会进行部署。</span></p><p><span style="font-size: 14px;">对于督查组提出的“能源结构带来的环境问题依然严重，环境保护力度和成效与中央要求和群众期盼仍有较大差距”问题，山东立下了“依法依规、立行立改”“压实责任、确保实效”“举一反三、标本兼治”的三原则，坚决打好污染防治攻坚战。</span></p><p><span style="font-size: 14px;">此外，海南、吉林、四川、浙江、西藏、新疆、青海7省，也分别就督查整改列出了详细的时间表和任务图——</span></p><p><span style="font-size: 14px;">海南成立了9个调查组，由海南省政府常务副省长为组长牵头逐一厘清责任，严肃问责追责；</span></p><p><span style="font-size: 14px;">吉林省委副书记、省长景俊海调任当地的第二天就连夜主持召开环保督察反馈问题整改工作调度推进会；</span></p><p><span style="font-size: 14px;">四川省编制的整改方案已全部完成，并于近日报国务院，抄送国家环境保护督察办公室；</span></p><p><span style="font-size: 14px;">浙江省也部署各部门开展相关工作，按照省委书记车俊此前的表态，以此为契机，坚持整体推进、系统修复、标本兼治。</span></p><p><span style="font-size: 14px;">长安街知事发现，随着第一轮环保督察四个批次的逐渐开展，环保问责也越来越严厉。据环保部统计，截至去年年底，第四批督察组交办的40706件环境问题举报已基本办结，共立案处罚10806家，罚款54759万元；立案侦查335件，拘留424人；约谈4855人，问责6471人。</span></p><p><span style="font-size: 14px;">十八大以来，中国的生态环境治理走上了标本兼治的快速路。《大气污染防治行动计划》《水污染防治行动计划》《土壤污染防治行动计划》陆续出台；新修订的《环境保护法》颁布施行；《“十三五”生态环境保护规划》《控制污染物排放许可制实施方案》等接连发布。</span></p><p><span style="font-size: 14px;">党的十九大报告提出两个“再奋斗十五年”，其中均与环境保护有关系，包括：在全面建成小康社会的基础上，在奋斗十五年，基本实现社会主义现代化，生态环境根本转好，美丽中国目标基本实现；在基本实现现代化的基础上，再奋斗十五年，把我国建成富强民主文明和谐美丽的社会主义现代化强国。</span></p><p><span style="font-size: 14px;">正如习近平总书记提出的“绿水青山就是金山银山”，各地方党委、政府只要抱定“功成不必在我、功力必不唐捐”的决心，势必能打赢这场生态保卫战。</span></p><section class="" data-source="bj.96weixin.com" style="white-space: normal;line-height: 25.6px;"><section style="margin-top: 0.5em;margin-bottom: 0.5em;"></section></section>
                </div>',
  'shop_reg_closed' => '0',
  'lang' => 'zh_cn',
  'icp_number' => '',
  'icp_file' => '',
  'watermark' => '',
  'watermark_place' => '1',
  'watermark_alpha' => 65,
  'use_storage' => '1',
  'market_price_rate' => 1.1999999999999999555910790149937383830547332763671875,
  'rewrite' => '0',
  'integral_name' => '积分',
  'integral_scale' => 1,
  'integral_percent' => '1',
  'sn_prefix' => 'ECS',
  'comment_check' => '1',
  'no_picture' => 'images/no_picture.gif',
  'stats_code' => '',
  'cache_time' => 3600,
  'register_points' => '0',
  'enable_gzip' => '0',
  'top10_time' => 0,
  'timezone' => '8',
  'upload_size_limit' => '64',
  'cron_method' => '0',
  'comment_factor' => '0',
  'enable_order_check' => '1',
  'default_storage' => 1,
  'bgcolor' => '#FFFFFF',
  'visit_stats' => 'on',
  'send_mail_on' => 'off',
  'auto_generate_gallery' => '1',
  'retain_original_img' => '1',
  'member_email_validate' => '1',
  'message_board' => '1',
  'certificate_id' => '',
  'token' => '',
  'certi' => 'http://localhost/openapi/api.php',
  'send_verify_email' => '0',
  'ent_id' => '',
  'ent_ac' => '',
  'ent_sign' => '',
  'ent_email' => '',
  'logistics_trace' => '0',
  'date_format' => 'Y-m-d',
  'time_format' => 'Y-m-d H:i:s',
  'currency_format' => '￥%s元',
  'thumb_width' => 100,
  'thumb_height' => 100,
  'image_width' => 230,
  'image_height' => 230,
  'top_number' => 10,
  'history_number' => 5,
  'comments_number' => 5,
  'bought_goods' => 3,
  'article_number' => 8,
  'goods_name_length' => 7,
  'price_format' => '5',
  'page_size' => 10,
  'sort_order_type' => '0',
  'sort_order_method' => '0',
  'show_order_type' => '1',
  'attr_related_number' => '5',
  'goods_gallery_number' => 5,
  'article_title_length' => '16',
  'name_of_region_1' => '国家',
  'name_of_region_2' => '省',
  'name_of_region_3' => '市',
  'name_of_region_4' => '区',
  'search_keywords' => '',
  'related_goods_number' => '4',
  'help_open' => '1',
  'article_page_size' => '10',
  'page_style' => '1',
  'recommend_order' => '0',
  'index_ad' => 'sys',
  'can_invoice' => '1',
  'use_integral' => '1',
  'use_bonus' => '1',
  'use_surplus' => '1',
  'use_how_oos' => '1',
  'send_confirm_email' => '0',
  'send_ship_email' => '0',
  'send_cancel_email' => '0',
  'send_invalid_email' => '0',
  'order_pay_note' => '1',
  'order_unpay_note' => '1',
  'order_ship_note' => '1',
  'order_receive_note' => '1',
  'order_unship_note' => '1',
  'order_return_note' => '1',
  'order_invalid_note' => '1',
  'order_cancel_note' => '1',
  'invoice_content' => 'demo',
  'anonymous_buy' => '1',
  'min_goods_amount' => 0,
  'one_step_buy' => 0,
  'invoice_type' => 
  array (
    'type' => 
    array (
      0 => '1',
      1 => '2',
      2 => '',
    ),
    'rate' => 
    array (
      0 => 1,
      1 => 1.5,
      2 => 0,
    ),
  ),
  'stock_dec_time' => '0',
  'cart_confirm' => '3',
  'send_service_email' => '0',
  'show_goods_in_cart' => '3',
  'show_attr_in_cart' => '1',
  'smtp_host' => 'localhost',
  'smtp_port' => '25',
  'smtp_user' => '',
  'smtp_pass' => '',
  'smtp_mail' => '',
  'mail_charset' => 'UTF8',
  'mail_service' => '0',
  'smtp_ssl' => '0',
  'integrate_code' => 'ecshop',
  'integrate_config' => '',
  'hash_code' => '2bdf8f5de94eb897de54719fa4fb00a3',
  'template' => 'default',
  'install_date' => '1505023202',
  'ecs_version' => 'v3.6.0',
  'sms_user_name' => '',
  'sms_password' => '',
  'sms_auth_str' => '',
  'sms_domain' => '',
  'sms_count' => '',
  'sms_total_money' => '',
  'sms_balance' => '',
  'sms_last_request' => '',
  'affiliate' => 'a:3:{s:6:"config";a:7:{s:6:"expire";d:24;s:11:"expire_unit";s:4:"hour";s:11:"separate_by";i:0;s:15:"level_point_all";s:2:"5%";s:15:"level_money_all";s:2:"1%";s:18:"level_register_all";i:2;s:17:"level_register_up";i:60;}s:4:"item";a:4:{i:0;a:2:{s:11:"level_point";s:3:"60%";s:11:"level_money";s:3:"60%";}i:1;a:2:{s:11:"level_point";s:3:"30%";s:11:"level_money";s:3:"30%";}i:2;a:2:{s:11:"level_point";s:2:"7%";s:11:"level_money";s:2:"7%";}i:3;a:2:{s:11:"level_point";s:2:"3%";s:11:"level_money";s:2:"3%";}}s:2:"on";i:1;}',
  'captcha' => '12',
  'captcha_width' => '100',
  'captcha_height' => '20',
  'sitemap' => 'a:6:{s:19:"homepage_changefreq";s:6:"hourly";s:17:"homepage_priority";s:3:"0.9";s:19:"category_changefreq";s:6:"hourly";s:17:"category_priority";s:3:"0.8";s:18:"content_changefreq";s:6:"weekly";s:16:"content_priority";s:3:"0.7";}',
  'points_rule' => '',
  'flash_theme' => 'dynfocus',
  'stylename' => '',
  'show_goodssn' => '1',
  'show_brand' => '1',
  'show_goodsweight' => '1',
  'show_goodsnumber' => '1',
  'show_addtime' => '1',
  'goodsattr_style' => '1',
  'show_marketprice' => '1',
  'sms_shop_mobile' => '',
  'sms_order_placed' => '0',
  'sms_order_payed' => '0',
  'sms_order_payed_to_customer' => '0',
  'sms_order_shipped' => '0',
  'snlist_code' => '{"erp":"goods_1109","fy":"goods_1137","taodali":"goods_1103","HDT":"goods_1500"}',
  'message_check' => '1',
  'sms_sign' => '',
  'default_sms_sign' => '',
  'best_number' => 3,
  'new_number' => 3,
  'hot_number' => 3,
  'promote_number' => 3,
);
?>